# Generated by Django 2.0.1 on 2018-01-26 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(verbose_name='date of the courses beginning ')),
                ('end_date', models.DateTimeField(verbose_name='date of the courses ending')),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geekhub.Course'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
