# Generated by Django 2.0.1 on 2018-02-02 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekhub', '0002_auto_20180126_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='publish date')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='students',
            old_name='course_name',
            new_name='course_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.AddField(
            model_name='course',
            name='descriptions',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=[''], size=None),
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(help_text='date of the courses beginning '),
        ),
    ]
