# Generated by Django 2.0.1 on 2018-02-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekhub', '0003_auto_20180202_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='descriptions',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
