# Generated by Django 2.0.1 on 2018-02-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekhub', '0005_auto_20180202_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_name',
        ),
    ]
