# Generated by Django 2.0.1 on 2018-02-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekhub', '0006_remove_student_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
