# Generated by Django 2.0.1 on 2018-02-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekhub', '0007_auto_20180203_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_id',
        ),
    ]
